BEGIN;

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  company TEXT,
  status TEXT NOT NULL CHECK (status IN ('new', 'contacted', 'qualified', 'proposal', 'won', 'lost')),
  source TEXT NOT NULL CHECK (source IN ('website', 'referral', 'social', 'cold', 'event', 'partner')),
  email TEXT,
  phone TEXT,
  last_activity TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_last_activity_desc ON leads (last_activity DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_source ON leads (source);

INSERT INTO leads (ref, name, company, status, source, email, phone, last_activity, created_at)
VALUES
  ('LEAD-2025-001', 'Amelia Winters', 'Brightside Labs', 'new', 'website', 'amelia@brightside.io', '+1-555-0101', NOW() - INTERVAL '2 days', NOW() - INTERVAL '32 days'),
  ('LEAD-2025-002', 'Zayn Malik', 'Northwind Traders', 'contacted', 'referral', 'zayn@northwindtraders.com', '+1-555-0102', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '28 days'),
  ('LEAD-2025-003', 'Sara Malik', 'Blue Horizon Media', 'qualified', 'social', 'sara@bluehorizon.io', '+44-20-555-0103', NOW() - INTERVAL '1 day', NOW() - INTERVAL '21 days'),
  ('LEAD-2025-004', 'Aqib Hanif', 'Vertex Analytics', 'proposal', 'partner', 'aqib@vertexanalytics.co', '+971-4-555-0104', NOW() - INTERVAL '12 hours', NOW() - INTERVAL '18 days'),
  ('LEAD-2025-005', 'Maria Costa', 'Edgewave Digital', 'won', 'referral', 'maria@edgewave.digital', '+34-91-555-0105', NOW() - INTERVAL '4 days', NOW() - INTERVAL '40 days'),
  ('LEAD-2025-006', 'Noor Ali', 'Skyline Ventures', 'contacted', 'event', 'noor@skylineventures.io', '+92-21-555-0106', NOW() - INTERVAL '8 hours', NOW() - INTERVAL '12 days'),
  ('LEAD-2025-007', 'David Green', 'Summit Retail', 'qualified', 'website', 'david@summitretail.com', '+1-555-0107', NOW() - INTERVAL '3 days', NOW() - INTERVAL '27 days'),
  ('LEAD-2025-008', 'Elena Petrova', 'Nova Robotics', 'proposal', 'partner', 'elena@novarobotics.eu', '+7-495-555-0108', NOW() - INTERVAL '16 hours', NOW() - INTERVAL '15 days'),
  ('LEAD-2025-009', 'Sameer Khan', 'J & A International', 'won', 'referral', 'sameer@jaint.com', '+92-21-555-0109', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '9 days'),
  ('LEAD-2025-010', 'Olivia Chen', 'Pacific Dynamics', 'lost', 'cold', 'olivia@pacificdynamics.co', '+1-555-0110', NOW() - INTERVAL '8 days', NOW() - INTERVAL '50 days'),
  ('LEAD-2025-011', 'Lucas Meyer', 'Synergy Cloud', 'new', 'social', 'lucas@synergycloud.de', '+49-30-555-0111', NOW() - INTERVAL '18 hours', NOW() - INTERVAL '4 days'),
  ('LEAD-2025-012', 'Haroon Iqbal', 'Prime Logistics', 'proposal', 'event', 'haroon@primelogistics.pk', '+92-42-555-0112', NOW() - INTERVAL '2 days', NOW() - INTERVAL '19 days')
ON CONFLICT (ref) DO NOTHING;

COMMIT;
